CMAKE_MINIMUM_REQUIRED (VERSION 2.8)

PROJECT (GX CUDA CXX Fortran)
SET (GX_BINARY_DIR_SRC ${GX_SOURCE_DIR}/build)

SET (CMAKE_CXX_STANDARD_LIBRARIES -lstdc++)

INCLUDE (Host_System_Setup.cmake)
INCLUDE (Package_Search.cmake)

INCLUDE_DIRECTORIES (src)
INCLUDE_DIRECTORIES (include)
INCLUDE_DIRECTORIES (${CUDA_INC})
INCLUDE_DIRECTORIES (/usr/include)

FILE (GLOB SRC_FILES src/*.cu)
FILE (GLOB HEADER_FILES include/*.h)

FOREACH (NVCC_IND ${NVCC_FLAGS})
  MESSAGE (${NVCC_IND})
ENDFOREACH ()

ADD_EXECUTABLE (gx ${SRC_FILES} ${HEADER_FILES})
TARGET_INCLUDE_DIRECTORIES (gx PUBLIC ${INCLUDE_LIST} PUBLIC ${CUDA_INC} PUBLIC /usr/include)
TARGET_LINK_LIBRARIES (gx PUBLIC ${LIBRARY_LINK_LIST})
TARGET_COMPILE_OPTIONS (gx PUBLIC ${NVCC_FLAGS})
SET_TARGET_PROPERTIES (gx PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${GX_SOURCE_DIR})
SET_TARGET_PROPERTIES (gx PROPERTIES LINKER_LANGUAGE CUDA)

#ADD_EXECUTABLE (unit_tests grids_test.cpp test.cpp ${SRC_FILES} ${INCLUDE_FILES})
#ADD_EXECUTABLE (unit_tests grids_test.cpp test.cpp fake_grids.h fake_grids.cpp)
#TARGET_INCLUDE_DIRECTORIES (unit_tests PUBLIC /home/mfmartin/proc_comments_gx/include PUBLIC ${INCLUDE_LIST})
#TARGET_COMPILE_OPTIONS (unit_tests PUBLIC ${NVCC_FLAGS})
#TARGET_LINK_LIBRARIES (unit_tests PUBLIC ${CUDA_LIB} ${LIBRARY_LINK_LIST})
#SET_PROPERTY (TARGET unit_tests PROPERTY CXX_STANDARD 11)
#SET_TARGET_PROPERTIES (unit_tests PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${UNIT_TESTS_SOURCE_DIR})
