INCLUDE (FindPkgConfig)
#SET (ENV{PKG_CONFIG_PATH} $ENV{PKG_CONFIG_PATH}:/usr/lib/pkgconfig)

PKG_CHECK_MODULES (NETCDF netcdf)
IF (NETCDF_FOUND)
  LIST (APPEND INCLUDE_LIST ${NETCDF_INCLUDEDIR})
  FOREACH (NETCDF_LIB_IND ${NETCDF_LINK_LIBRARIES})
    LIST (APPEND LIBRARY_LINK_LIST ${NETCDF_LIB_IND})
  ENDFOREACH ()
ENDIF ()

PKG_CHECK_MODULES (CUFFTW cufftw-10.2)
IF (CUFFTW_FOUND)
  LIST (APPEND INCLUDE_LIST ${CUFFTW_INCLUDEDIR})
  FOREACH (CUFFTW_LIB_IND ${CUFFTW_LINK_LIBRARIES})
    LIST (APPEND LIBRARY_LINK_LIST ${CUFFTW_LIB_IND})
  ENDFOREACH ()
ENDIF ()

PKG_CHECK_MODULES (CUFFT cufft-10.2)
IF (CUFFT_FOUND)
  LIST (APPEND INCLUDE_LIST ${CUFFT_INCLUDEDIR})
  FOREACH (CUFFT_LIB_IND ${CUFFT_LINK_LIBRARIES})
    LIST (APPEND LIBRARY_LINK_LIST ${CUFFT_LIB_IND})
  ENDFOREACH ()
ENDIF ()

PKG_CHECK_MODULES (CUSOLVER cusolver-10.2)
IF (CUSOLVER_FOUND)
  LIST (APPEND INCLUDE_LIST ${CUSOLVER_INCLUDEDIR})
  FOREACH (CUSOLVER_LIB_IND ${CUSOLVER_LINK_LIBRARIES})
    LIST (APPEND LIBRARY_LINK_LIST ${CUSOLVER_LIB_IND})
  ENDFOREACH ()
ENDIF ()

PKG_CHECK_MODULES (CUBLAS cublas-10)
IF (CUBLAS_FOUND)
  LIST (APPEND INCLUDE_LIST ${CUBLAS_INCLUDEDIR})
  FOREACH (CUBLAS_LIB_IND ${CUBLAS_LINK_LIBRARIES})
    LIST (APPEND LIBRARY_LINK_LIST ${CUBLAS_LIB_IND})
  ENDFOREACH ()
ENDIF ()

FIND_LIBRARY (CUBLAS_LIBRARY
  NAMES libcublas_static.a libcublas.so
  HINTS ${NETCDF_LIBDIR} ${NETCDF_LIBRARY_DIRS})
#MESSAGE ("netcdf --> ${NETCDF_LIBDIR}")
#MESSAGE ("cublas --> ${CUBLAS_LIBRARY}")
LIST (APPEND LIBRARY_LINK_LIST ${CUBLAS_LIBRARY})

PKG_CHECK_MODULES (GSL gsl)
IF (GSL_FOUND)
  LIST (APPEND INCLUDE_LIST ${GSL_INCLUDEDIR})
  FOREACH (GSL_LIB_IND ${GSL_LINK_LIBRARIES})
    LIST (APPEND LIBRARY_LINK_LIST ${GSL_LIB_IND})
  ENDFOREACH ()
ENDIF ()

LIST (APPEND LIBRARY_LINK_LIST /usr/local/cuda-10.2/targets/x86_64-linux/lib/libculibos.a)


