#!/usr/bin/env python

import matplotlib.pyplot as plt
import numpy as np
import inspect
from scipy.interpolate import interp1d, splrep, splev
import sys


# Read in GIST file
f = open(sys.argv[1],'r')
lines = f.readlines()
f.close()

splitline = lines[0].split()
gist_ntheta = int(splitline[0])
pol_turns = float(splitline[1])
shat = float(splitline[2])
drhodpsi = float(splitline[3])

numLines = gist_ntheta*2+1
numCols = 10 # Number of geometric factors in GIST file

print "This GIST file has %d grid points per 2*pi segment" % int((numLines-1)/pol_turns)
print ""

gist_data = np.zeros([numLines,numCols])
for irow in range(numLines):
    splitline = lines[irow+1].split()
    for icol in range(numCols):
        gist_data[irow,icol] = float(splitline[icol])

theta = gist_data[:,0]
bmag = gist_data[:,1]
gradpar = gist_data[:,2]
gds2 = gist_data[:,3]
gds21 = gist_data[:,4]
gds22 = gist_data[:,5]
cvdrift = gist_data[:,6]
cvdrift0 = gist_data[:,7]
gbdrift = gist_data[:,8]
gbdrift0 = gist_data[:,9]

plt.plot(theta,bmag)
plt.show()
